"""empty message

Revision ID: 87584964507a
Revises: 9297e1f49104
Create Date: 2026-03-28 17:42:00.764054

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '87584964507a'
down_revision: Union[str, Sequence[str], None] = '9297e1f49104'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'calls',
        sa.Column(
            'is_private',
            sa.Boolean(),
            nullable=False,
            server_default=sa.false()
        )
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('calls', 'is_private')
    # ### end Alembic commands ###
