"""empty message

Revision ID: f98be769cf83
Revises: dc3978966607
Create Date: 2026-04-05 22:41:54.704298

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f98be769cf83'
down_revision: Union[str, Sequence[str], None] = 'dc3978966607'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('calls', 'is_private')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('calls', sa.Column('is_private', sa.BOOLEAN(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
